config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Create Tasks
  get 'tasks/new' => 'tasks#new'
  post 'tasks' => 'tasks#create'

  # Read tasks
  get 'tasks' => 'tasks#index'
  get 'tasks/:id' => 'tasks#show', as: :task

  # Update Tasks
  get 'tasks/:id/edit' => 'tasks#edit', as: :edit
  patch 'tasks/:id' => 'tasks#update'

  # Delete tasks
  delete 'tasks/:id' => 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]



  def index         # GET /tasks
    @tasks = Task.all
  end

  def show          # GET /tasks/:id
  end

  def new           # GET /tasks/new
   @task = Task.new
  end

  def create        # POST /tasks
    @task = Task.new(task_params)
    @task.save
    redirect_to action: "index"
  end

  def edit          # GET /tasks/:id/edit
  end

  def update        # PATCH /tasks/:id
     @task.update(task_params)
     redirect_to action: "show"
  end

  def destroy       # DELETE /tasks/:id
    @task.destroy
    redirect_to action: "index"
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ol>
  <% @tasks.each do |task| %>
  <li>
    <% completed = task.completed? ? 'checked.svg' : "empty.svg"  %>
     <%= image_tag completed, alt: "alttext", width: '20px' %>
    <%= link_to task.title, task_path(task)  %>
    <%= link_to "Delete", task_path(task), method: :delete,
      data: { confirm: "Are you sure?" } %>
  </li>
  <% end %>
</ol>

<%= link_to "+ Add a new task", tasks_new_path  %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task no. <%= @task.id %></h1>
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<% completed = @task.completed? ? "Done" : "Not done yet" %>
<p><%= completed %></p>
<%= link_to "Edit task", edit_path(@task)  %>
<%= link_to "Back to list", tasks_path  %>